// <auto-generated />
using System;
using BlazorHrFaq.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorHrFaq.Database.Migrations
{
    [DbContext(typeof(DatabaseDb))]
    [Migration("20240826151532_JesperDb07")]
    partial class JesperDb07
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorHrFaq.Database.Model.Faq", b =>
                {
                    b.Property<Guid>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HitCount")
                        .HasColumnType("int");

                    b.Property<string>("SearchWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FaqId");

                    b.ToTable("Faq");

                    b.HasData(
                        new
                        {
                            FaqId = new Guid("aabdf4ea-ea4c-40a0-a47e-e2880ffb0f13"),
                            Answer = "Hello world",
                            CreateDatetime = new DateTime(2024, 8, 26, 17, 15, 32, 522, DateTimeKind.Local).AddTicks(5981),
                            HitCount = 1,
                            SearchWords = "Hej"
                        },
                        new
                        {
                            FaqId = new Guid("00eae4de-014c-4ace-adcf-e38bcb8f6efc"),
                            Answer = "Hello world",
                            CreateDatetime = new DateTime(2024, 8, 26, 17, 15, 32, 522, DateTimeKind.Local).AddTicks(6026),
                            HitCount = 1,
                            SearchWords = "Jesper"
                        },
                        new
                        {
                            FaqId = new Guid("4bfc4eb2-c496-4e8f-8c24-1986858f1689"),
                            Answer = "Hello world",
                            CreateDatetime = new DateTime(2024, 8, 26, 17, 15, 32, 522, DateTimeKind.Local).AddTicks(6029),
                            HitCount = 1,
                            SearchWords = "Test"
                        });
                });

            modelBuilder.Entity("BlazorHrFaq.Database.Model.MatchData", b =>
                {
                    b.Property<Guid>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MatchId");

                    b.ToTable("Match");
                });
#pragma warning restore 612, 618
        }
    }
}
