// <auto-generated />
using System;
using BlazorHrFaq.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorHrFaq.Database.Migrations
{
    [DbContext(typeof(DatabaseDb))]
    [Migration("20240824163102_JesperDb05")]
    partial class JesperDb05
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorHrFaq.Database.Model.Faq", b =>
                {
                    b.Property<Guid>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HitCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SearchWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FaqId");

                    b.ToTable("Faq");

                    b.HasData(
                        new
                        {
                            FaqId = new Guid("16684a83-f85f-42c0-be95-26587dc387bb"),
                            Answer = "Hello world",
                            HitCount = 1,
                            LastUpdate = new DateTime(2024, 8, 24, 18, 31, 2, 0, DateTimeKind.Local).AddTicks(6443),
                            SearchWords = "Hej"
                        },
                        new
                        {
                            FaqId = new Guid("9c58e705-0288-4a0d-961c-d71b6ff35886"),
                            Answer = "Hello world",
                            HitCount = 1,
                            LastUpdate = new DateTime(2024, 8, 24, 18, 31, 2, 0, DateTimeKind.Local).AddTicks(6507),
                            SearchWords = "Jesper"
                        },
                        new
                        {
                            FaqId = new Guid("c586c144-7d0f-4efa-a899-7e111f216079"),
                            Answer = "Hello world",
                            HitCount = 1,
                            LastUpdate = new DateTime(2024, 8, 24, 18, 31, 2, 0, DateTimeKind.Local).AddTicks(6510),
                            SearchWords = "Test"
                        });
                });

            modelBuilder.Entity("BlazorHrFaq.Database.Model.MatchData", b =>
                {
                    b.Property<Guid>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MatchId");

                    b.ToTable("Match");
                });
#pragma warning restore 612, 618
        }
    }
}
