//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorHrFaq.TextHelper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextHelperResFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextHelperResFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorHrFaq.TextHelper.TextHelperResFile", typeof(TextHelperResFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit spørgsmål findes ikke i systemet hos {sitename} - Prøv igen: {searchword}.
        /// </summary>
        public static string NotAnswersToUser {
            get {
                return ResourceManager.GetString("NotAnswersToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stille spørgsmål her..
        /// </summary>
        public static string PlaceholderTextInput {
            get {
                return ResourceManager.GetString("PlaceholderTextInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jesper HR Faq.
        /// </summary>
        public static string Sitename {
            get {
                return ResourceManager.GetString("Sitename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ønsker at få besvaret spørgsmålet..
        /// </summary>
        public static string SubmitSearchInput {
            get {
                return ResourceManager.GetString("SubmitSearchInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hr FAQ.
        /// </summary>
        public static string TitleName {
            get {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ønsker at du at opnå besvarelse på dine spørgsmål - {titlename} besvare dine spørgsmål!.
        /// </summary>
        public static string TopDeckText {
            get {
                return ResourceManager.GetString("TopDeckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {titlename} - Still din spørgsmål..
        /// </summary>
        public static string TopTitleText {
            get {
                return ResourceManager.GetString("TopTitleText", resourceCulture);
            }
        }
    }
}
