//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrFaq.Application.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextHelperResFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextHelperResFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HrFaq.Application.Helper.TextHelperResFile", typeof(TextHelperResFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilføj Information.
        /// </summary>
        public static string AddInformation {
            get {
                return ResourceManager.GetString("AddInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilføj tekst til indholdet.
        /// </summary>
        public static string AddText {
            get {
                return ResourceManager.GetString("AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilføj url til billede, link eller PDF..
        /// </summary>
        public static string AddValue {
            get {
                return ResourceManager.GetString("AddValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spørgsmålet som bruger stiller. Du kan lave flere ved at bruge &quot; , &quot;.
        /// </summary>
        public static string InputAnswer {
            get {
                return ResourceManager.GetString("InputAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kan tilføj din match ord her hvis du gør brug af det flere steder..
        /// </summary>
        public static string InputAnswerTwo {
            get {
                return ResourceManager.GetString("InputAnswerTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit spørgsmål findes ikke i systemet hos {sitename} - Prøv igen: {searchword}.
        /// </summary>
        public static string NotAnswersToUser {
            get {
                return ResourceManager.GetString("NotAnswersToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stille spørgsmål her..
        /// </summary>
        public static string PlaceholderTextInput {
            get {
                return ResourceManager.GetString("PlaceholderTextInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søgning efter:.
        /// </summary>
        public static string SearchTextHome {
            get {
                return ResourceManager.GetString("SearchTextHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ønsker i/du flere svare tilbage?.
        /// </summary>
        public static string SettingAnswerMuli {
            get {
                return ResourceManager.GetString("SettingAnswerMuli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori område til firma - Fx bogholder vil kun få svar tilbage som omhandler dem..
        /// </summary>
        public static string SettingCategori {
            get {
                return ResourceManager.GetString("SettingCategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ønsker du at få linket til at åben i ny fane?.
        /// </summary>
        public static string SettingLink {
            get {
                return ResourceManager.GetString("SettingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kræver system log ind?.
        /// </summary>
        public static string SettingLoginUser {
            get {
                return ResourceManager.GetString("SettingLoginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ønsker rapport over spørgsmål (Ingen bruger data).
        /// </summary>
        public static string SettingRapport {
            get {
                return ResourceManager.GetString("SettingRapport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjerne indholdet fra svarne..
        /// </summary>
        public static string SettingRemoveMatchWords {
            get {
                return ResourceManager.GetString("SettingRemoveMatchWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opdater information.
        /// </summary>
        public static string SettingUpdate {
            get {
                return ResourceManager.GetString("SettingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jesper HR Faq.
        /// </summary>
        public static string Sitename {
            get {
                return ResourceManager.GetString("Sitename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ønsker at få besvaret spørgsmålet..
        /// </summary>
        public static string SubmitSearchInput {
            get {
                return ResourceManager.GetString("SubmitSearchInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hr FAQ.
        /// </summary>
        public static string TitleName {
            get {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lave alle dine spørgsmål klar til jeres medarbejder og være klar med de bedste besvarelse..
        /// </summary>
        public static string TopDeckAnswer {
            get {
                return ResourceManager.GetString("TopDeckAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ønsker at du at opnå besvarelse på dine spørgsmål - {titlename} besvare dine spørgsmål!.
        /// </summary>
        public static string TopDeckText {
            get {
                return ResourceManager.GetString("TopDeckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her vil du kun tildele links, billeder og pdf filer til..
        /// </summary>
        public static string TopDeckTextMatch {
            get {
                return ResourceManager.GetString("TopDeckTextMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprettelse af spørgsmål til {sitename}.
        /// </summary>
        public static string TopTitleAnswer {
            get {
                return ResourceManager.GetString("TopTitleAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {titlename} - Still din spørgsmål..
        /// </summary>
        public static string TopTitleText {
            get {
                return ResourceManager.GetString("TopTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opret match indhold.
        /// </summary>
        public static string TopTitleTextMatch {
            get {
                return ResourceManager.GetString("TopTitleTextMatch", resourceCulture);
            }
        }
    }
}
