// <auto-generated />
using System;
using BlazorHrFaq.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorHrFaq.Database.Migrations
{
    [DbContext(typeof(DatabaseDb))]
    partial class DatabaseDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorHrFaq.Database.Model.Faq", b =>
                {
                    b.Property<Guid>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HitCount")
                        .HasColumnType("int");

                    b.Property<string>("SearchWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FaqId");

                    b.ToTable("Faq");

                    b.HasData(
                        new
                        {
                            FaqId = new Guid("ab149676-7460-4acb-8709-d0c5da325a1d"),
                            Answer = "Hello world",
                            CreateDatetime = new DateTime(2024, 8, 24, 18, 37, 48, 754, DateTimeKind.Local).AddTicks(3835),
                            HitCount = 1,
                            SearchWords = "Hej"
                        },
                        new
                        {
                            FaqId = new Guid("27554c9c-9908-4502-bd86-eab867007cca"),
                            Answer = "Hello world",
                            CreateDatetime = new DateTime(2024, 8, 24, 18, 37, 48, 754, DateTimeKind.Local).AddTicks(3892),
                            HitCount = 1,
                            SearchWords = "Jesper"
                        },
                        new
                        {
                            FaqId = new Guid("aad30447-2a5c-42b5-9ffb-911ce6992110"),
                            Answer = "Hello world",
                            CreateDatetime = new DateTime(2024, 8, 24, 18, 37, 48, 754, DateTimeKind.Local).AddTicks(3895),
                            HitCount = 1,
                            SearchWords = "Test"
                        });
                });

            modelBuilder.Entity("BlazorHrFaq.Database.Model.MatchData", b =>
                {
                    b.Property<Guid>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MatchId");

                    b.ToTable("Match");
                });
#pragma warning restore 612, 618
        }
    }
}
