// <auto-generated />
using System;
using BlazorHrFaq.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorHrFaq.Database.Migrations
{
    [DbContext(typeof(DatabaseDb))]
    [Migration("20240901172659_JesperDb10")]
    partial class JesperDb10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorHrFaq.Database.Model.Faq", b =>
                {
                    b.Property<Guid>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HitCount")
                        .HasColumnType("int");

                    b.Property<string>("SearchWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FaqId");

                    b.ToTable("Faq");

                    b.HasData(
                        new
                        {
                            FaqId = new Guid("24112ecf-afc7-4ae8-bfe0-850a90b52847"),
                            Answer = "Hello world",
                            CreateDatetime = new DateTime(2024, 9, 1, 19, 26, 58, 787, DateTimeKind.Local).AddTicks(9433),
                            HitCount = 1,
                            SearchWords = "Hej"
                        },
                        new
                        {
                            FaqId = new Guid("4157d7bd-aacf-4ad7-8a0e-0f9413df9e39"),
                            Answer = "Hello world",
                            CreateDatetime = new DateTime(2024, 9, 1, 19, 26, 58, 787, DateTimeKind.Local).AddTicks(9480),
                            HitCount = 1,
                            SearchWords = "Jesper"
                        },
                        new
                        {
                            FaqId = new Guid("5a2a38df-5878-46ab-a1fc-279221db1319"),
                            Answer = "Hello world",
                            CreateDatetime = new DateTime(2024, 9, 1, 19, 26, 58, 787, DateTimeKind.Local).AddTicks(9483),
                            HitCount = 1,
                            SearchWords = "Test"
                        });
                });

            modelBuilder.Entity("BlazorHrFaq.Database.Model.MatchData", b =>
                {
                    b.Property<Guid>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MatchId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("HrFaq.Database.Model.SettingInfo", b =>
                {
                    b.Property<Guid>("SettingInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AnswerMuli")
                        .HasColumnType("bit");

                    b.Property<bool>("CompanyCategory")
                        .HasColumnType("bit");

                    b.Property<bool>("LinkTarget")
                        .HasColumnType("bit");

                    b.Property<bool>("LoginUser")
                        .HasColumnType("bit");

                    b.Property<bool>("RemoveMatchWords")
                        .HasColumnType("bit");

                    b.Property<bool>("StatusRapport")
                        .HasColumnType("bit");

                    b.HasKey("SettingInfoId");

                    b.ToTable("SettingInfo");

                    b.HasData(
                        new
                        {
                            SettingInfoId = new Guid("d5b95c63-8fcb-4d28-8056-4a03a238f077"),
                            AnswerMuli = true,
                            CompanyCategory = false,
                            LinkTarget = true,
                            LoginUser = false,
                            RemoveMatchWords = false,
                            StatusRapport = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
