// <auto-generated />
using System;
using BlazorHrFaq.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorHrFaq.Database.Migrations
{
    [DbContext(typeof(DatabaseDb))]
    partial class DatabaseDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorHrFaq.Database.Model.Faq", b =>
                {
                    b.Property<Guid>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HitCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("SearchWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FaqId");

                    b.ToTable("Faq");

                    b.HasData(
                        new
                        {
                            FaqId = new Guid("0868c46c-1560-4258-b9a1-e4d6a698bc8e"),
                            Answer = "Hello world",
                            HitCount = 1,
                            LastUpdate = new DateTime(2024, 8, 17, 21, 31, 19, 277, DateTimeKind.Local).AddTicks(8190),
                            Priority = 1,
                            SearchWords = "Hej"
                        },
                        new
                        {
                            FaqId = new Guid("8389b381-da41-4ba8-870a-a9b5ed138ef2"),
                            Answer = "Hello world",
                            HitCount = 1,
                            LastUpdate = new DateTime(2024, 8, 17, 21, 31, 19, 277, DateTimeKind.Local).AddTicks(8239),
                            Priority = 1,
                            SearchWords = "Jesper"
                        },
                        new
                        {
                            FaqId = new Guid("cd5d5a55-74af-41a4-804f-9c1b8e6bfd49"),
                            Answer = "Hello world",
                            HitCount = 1,
                            LastUpdate = new DateTime(2024, 8, 17, 21, 31, 19, 277, DateTimeKind.Local).AddTicks(8242),
                            Priority = 1,
                            SearchWords = "Test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
